# YAML is Used  Hierarchy

# YAML means YAML Ain't markUp language use for Config file or Data Serialization

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring2_4
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
  banner:
    location: classpath:banner.txt    

server:
  port: 8002